version: '3.7'
services:
  mysql:  # This is the service name, and can be any valid name (e.g., mysql)
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "8443:8443"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  mysql_data:
